# scp -rp mtomov13@ncfws12.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/ConLearn/glmOutput neural 
#rsync -avh -e ssh mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/ConLearn/glmOutput/mean.nii neural/mean.nii
#for i in {1..9}
#do
#    mkdir neural/model$i
#    rsync -avh -e ssh mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/ConLearn/glmOutput/model$i/con* neural/model$i/
#done
#

#
# COPIES STUFF FROM NCF
# WARNING: DO NOT UPLOAD ON GITHUB!! CONTAINS PASSWORDS!!!
#

# STEP 1: install sshpass
# do it the hard way -- download from http://sourceforge.net/projects/sshpass/files/sshpass/1.05/sshpass-1.05.tar.gz
# then ./configure
# then sudo make install
# which sshpass <-- to find out where it is, and use that path in the --rsh thing below


#rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_hippocampus_contextId_training_only_BGYIKSYGGW.mat classify_context_heldout_20
#rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_hippocampus_contextId_training_only_CBJISSDBDD.mat classify_context_heldout_20
#rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_ofc_contextId_training_only_KBHHVPMSVY.mat classify_context_heldout_20
#rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_ofc_contextId_training_only_MNWHDWSMKR.mat classify_context_heldout_20
#rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_striatum_contextId_training_only_PMIRDCKBDY.mat classify_context_heldout_20
#rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_striatum_contextId_training_only_HOZDXPMBJL.mat classify_context_heldout_20
#rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_vmpfc_contextId_training_only_WTVWTMFUGZ.mat classify_context_heldout_20
#rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_vmpfc_contextId_training_only_MZFVNHDCUL.mat classify_context_heldout_20
#rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_bg_contextId_training_only_OSKCGYMMUJ.mat classify_context_heldout_20
#rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_bg_contextId_training_only_DLZFPTCRRG.mat classify_context_heldout_20
#rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_pallidum_contextId_training_only_OMFAQHSMUB.mat classify_context_heldout_20
#rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_pallidum_contextId_training_only_UALPSPXXPV.mat classify_context_heldout_20








rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_hippocampus_condition_ZAGAABEXLM.mat classify_heldout_trial_1
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_hippocampus_condition_HPEADGEBOW.mat classify_heldout_trial_1
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_ofc_condition_NTGYFJTHFC.mat classify_heldout_trial_1
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_ofc_condition_QJOJYPRDXM.mat classify_heldout_trial_1
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_striatum_condition_RRVUXGTXGW.mat classify_heldout_trial_1
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_striatum_condition_XAQDHBRJHP.mat classify_heldout_trial_1
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_vmpfc_condition_KNXPEFSXTH.mat classify_heldout_trial_1
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_vmpfc_condition_RZNYYIBOWJ.mat classify_heldout_trial_1
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_rlpfc_condition_DNOSVOODWD.mat classify_heldout_trial_1
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_rlpfc_condition_ZAIZRLLMUD.mat classify_heldout_trial_1
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_bg_condition_UHIVBSAPBW.mat classify_heldout_trial_1
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_bg_condition_JODLBISXUK.mat classify_heldout_trial_1
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_pallidum_condition_SXMSPRVPEE.mat classify_heldout_trial_1
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_pallidum_condition_JAWEBNJBJW.mat classify_heldout_trial_1
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_hippocampus_condition_HMYTSSARRH.mat classify_heldout_trial_2
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_hippocampus_condition_WUNGNJNRDT.mat classify_heldout_trial_2
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_ofc_condition_JZZYRXUIGV.mat classify_heldout_trial_2
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_ofc_condition_TTIYXTNGSS.mat classify_heldout_trial_2
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_striatum_condition_ZDBEJKHSHE.mat classify_heldout_trial_2
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_striatum_condition_VROYZBITOV.mat classify_heldout_trial_2
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_vmpfc_condition_RMQIWKZAMB.mat classify_heldout_trial_2
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_vmpfc_condition_AAFNMHYYDC.mat classify_heldout_trial_2
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_rlpfc_condition_FCDOEBYQXK.mat classify_heldout_trial_2
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_rlpfc_condition_SMCHAHKNZX.mat classify_heldout_trial_2
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_bg_condition_HGSVSLRONT.mat classify_heldout_trial_2
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_bg_condition_KUAWMVHVPM.mat classify_heldout_trial_2
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_pallidum_condition_QRYFRZFWSM.mat classify_heldout_trial_2
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_pallidum_condition_IHODFDGEWA.mat classify_heldout_trial_2
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_hippocampus_condition_WIURLWSOPP.mat classify_heldout_trial_3
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_hippocampus_condition_XOUCGUNLQC.mat classify_heldout_trial_3
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_ofc_condition_ZQUCOJIWHZ.mat classify_heldout_trial_3
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_ofc_condition_PTTJVRUHIT.mat classify_heldout_trial_3
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_striatum_condition_XAQJJOSNSU.mat classify_heldout_trial_3
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_striatum_condition_SLMYLPAJMP.mat classify_heldout_trial_3
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_vmpfc_condition_TWINLPYCPS.mat classify_heldout_trial_3
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_vmpfc_condition_XBHIVPSQAX.mat classify_heldout_trial_3
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_rlpfc_condition_LJGZRZDWAQ.mat classify_heldout_trial_3
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_rlpfc_condition_NJNMMWKFFZ.mat classify_heldout_trial_3
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_bg_condition_FSVIHJFTQK.mat classify_heldout_trial_3
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_bg_condition_HJPXSDCKSZ.mat classify_heldout_trial_3
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_pallidum_condition_GHROKGPEJW.mat classify_heldout_trial_3
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_pallidum_condition_ESDVMRDBZM.mat classify_heldout_trial_3
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_hippocampus_condition_QYKIIEGRPK.mat classify_heldout_trial_4
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_hippocampus_condition_MCGVMOOKEV.mat classify_heldout_trial_4
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_ofc_condition_RKZDJSKAII.mat classify_heldout_trial_4
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_ofc_condition_VPWFPWZBPO.mat classify_heldout_trial_4
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_striatum_condition_YESBSFUZKZ.mat classify_heldout_trial_4
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_striatum_condition_SKPAOORVTB.mat classify_heldout_trial_4
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_vmpfc_condition_TLNZHTBUMN.mat classify_heldout_trial_4
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_vmpfc_condition_GPYUERUIWD.mat classify_heldout_trial_4
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_rlpfc_condition_LHQRDOXQQN.mat classify_heldout_trial_4
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_rlpfc_condition_EZIXUHEGAJ.mat classify_heldout_trial_4
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_bg_condition_IPWSKKQRIC.mat classify_heldout_trial_4
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_bg_condition_DAMKJWFZHH.mat classify_heldout_trial_4
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_pallidum_condition_NJCWWAPJUF.mat classify_heldout_trial_4
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_pallidum_condition_MTSZNSSVDW.mat classify_heldout_trial_4
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_hippocampus_condition_VGJXGHHFSL.mat classify_heldout_trial_5
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_hippocampus_condition_CBJNPQZPKD.mat classify_heldout_trial_5
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_ofc_condition_KDQAHXOQWI.mat classify_heldout_trial_5
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_ofc_condition_BCEMJJORGP.mat classify_heldout_trial_5
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_striatum_condition_FCFJDEFAVG.mat classify_heldout_trial_5
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_striatum_condition_EZBXNHXOHN.mat classify_heldout_trial_5
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_vmpfc_condition_PCYEUIVYZW.mat classify_heldout_trial_5
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_vmpfc_condition_CRBVUQRLCF.mat classify_heldout_trial_5
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_rlpfc_condition_DEUEEXQTVE.mat classify_heldout_trial_5
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_rlpfc_condition_DRGCQCAPZC.mat classify_heldout_trial_5
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_bg_condition_ULEQJPJFLY.mat classify_heldout_trial_5
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_bg_condition_UAZYXQFYBT.mat classify_heldout_trial_5
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_pallidum_condition_TLJWNGQCQZ.mat classify_heldout_trial_5
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_pallidum_condition_WAPVNXMULG.mat classify_heldout_trial_5
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_hippocampus_condition_UMMMITCTYA.mat classify_heldout_trial_6
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_hippocampus_condition_OXBKCEKAML.mat classify_heldout_trial_6
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_ofc_condition_NFAMGFMSQV.mat classify_heldout_trial_6
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_ofc_condition_YDXSCCGMUT.mat classify_heldout_trial_6
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_striatum_condition_ABVVLUXJUJ.mat classify_heldout_trial_6
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_striatum_condition_HMQGAAAGKK.mat classify_heldout_trial_6
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_vmpfc_condition_TMUBJJSXHB.mat classify_heldout_trial_6
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_vmpfc_condition_QKCEMMBAOT.mat classify_heldout_trial_6
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_rlpfc_condition_EGIIZGLLJN.mat classify_heldout_trial_6
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_rlpfc_condition_QAAVBOECWG.mat classify_heldout_trial_6
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_bg_condition_UWKCZONEXW.mat classify_heldout_trial_6
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_bg_condition_RTSQQXROMO.mat classify_heldout_trial_6
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_pallidum_condition_GHWVTCDJNB.mat classify_heldout_trial_6
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_pallidum_condition_IIKTPEZTKZ.mat classify_heldout_trial_6
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_hippocampus_condition_WLOAIRFOUJ.mat classify_heldout_trial_7
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_hippocampus_condition_QAFPZCHYCV.mat classify_heldout_trial_7
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_ofc_condition_PZBSZUISPC.mat classify_heldout_trial_7
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_ofc_condition_KUWURWKMFP.mat classify_heldout_trial_7
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_striatum_condition_PIGWUYNZAE.mat classify_heldout_trial_7
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_striatum_condition_NANCVESUWJ.mat classify_heldout_trial_7
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_vmpfc_condition_FQSXSSULQU.mat classify_heldout_trial_7
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_vmpfc_condition_RIOTHNZBUC.mat classify_heldout_trial_7
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_rlpfc_condition_GLXKTFUWEO.mat classify_heldout_trial_7
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_rlpfc_condition_NFHCSFRGXU.mat classify_heldout_trial_7
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_bg_condition_UXWIAHETEC.mat classify_heldout_trial_7
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_bg_condition_RXFNGUWHJD.mat classify_heldout_trial_7
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_pallidum_condition_TWGTORCSRB.mat classify_heldout_trial_7
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_pallidum_condition_DZLLJJALWU.mat classify_heldout_trial_7
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_hippocampus_condition_PTQGFFFNWB.mat classify_heldout_trial_8
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_hippocampus_condition_OEWDXBMVDG.mat classify_heldout_trial_8
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_ofc_condition_NXWDAUGTHH.mat classify_heldout_trial_8
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_ofc_condition_VIOBLMGBVR.mat classify_heldout_trial_8
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_striatum_condition_TPMUIYODJF.mat classify_heldout_trial_8
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_striatum_condition_MZZIQZVYSK.mat classify_heldout_trial_8
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_vmpfc_condition_CISOQYHCNZ.mat classify_heldout_trial_8
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_vmpfc_condition_CNMPNCSDVI.mat classify_heldout_trial_8
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_rlpfc_condition_DUJZKROUQV.mat classify_heldout_trial_8
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_rlpfc_condition_USXQXGIYGU.mat classify_heldout_trial_8
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_bg_condition_WFRRJKATJF.mat classify_heldout_trial_8
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_bg_condition_LSZEPHGCDL.mat classify_heldout_trial_8
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_pallidum_condition_NMLJFZBAKF.mat classify_heldout_trial_8
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_pallidum_condition_KAGYQQYSXR.mat classify_heldout_trial_8
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_hippocampus_condition_HWBJDXGXBV.mat classify_heldout_trial_9
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_hippocampus_condition_TISPJZLIQH.mat classify_heldout_trial_9
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_ofc_condition_MOEBJDKRQT.mat classify_heldout_trial_9
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_ofc_condition_JVLQKPQJYE.mat classify_heldout_trial_9
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_striatum_condition_DJERIELAKN.mat classify_heldout_trial_9
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_striatum_condition_XLHGXVBYXX.mat classify_heldout_trial_9
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_vmpfc_condition_GPGHWBDXXG.mat classify_heldout_trial_9
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_vmpfc_condition_JBCATNMZJH.mat classify_heldout_trial_9
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_rlpfc_condition_AVLZFFUZNB.mat classify_heldout_trial_9
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_rlpfc_condition_VAYHWQUKEW.mat classify_heldout_trial_9
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_bg_condition_SZYBWGIZMJ.mat classify_heldout_trial_9
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_bg_condition_HMYDBUFNNG.mat classify_heldout_trial_9
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_pallidum_condition_IXICYVXZUX.mat classify_heldout_trial_9
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_pallidum_condition_PTTGOTBKCS.mat classify_heldout_trial_9
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_hippocampus_condition_JKXIIKNFWA.mat classify_heldout_trial_10
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_hippocampus_condition_JJWINQIFIQ.mat classify_heldout_trial_10
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_ofc_condition_VVXDAHQDIG.mat classify_heldout_trial_10
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_ofc_condition_XCLGBGMLWD.mat classify_heldout_trial_10
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_striatum_condition_GDJXJLRFLO.mat classify_heldout_trial_10
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_striatum_condition_WHVXMDAUWZ.mat classify_heldout_trial_10
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_vmpfc_condition_DVGGKTITTX.mat classify_heldout_trial_10
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_vmpfc_condition_EATVYDKKQL.mat classify_heldout_trial_10
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_rlpfc_condition_QOYLFSMNKQ.mat classify_heldout_trial_10
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_rlpfc_condition_NKVZASACOY.mat classify_heldout_trial_10
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_bg_condition_CWLWODIABQ.mat classify_heldout_trial_10
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_bg_condition_FVVSYTMNZF.mat classify_heldout_trial_10
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_pallidum_condition_HCKFWTPQXB.mat classify_heldout_trial_10
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_pallidum_condition_GENMXVHUBY.mat classify_heldout_trial_10
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_hippocampus_condition_JCPOOYUQRK.mat classify_heldout_trial_11
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_hippocampus_condition_THNMZOILBC.mat classify_heldout_trial_11
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_ofc_condition_CGWYLACFRU.mat classify_heldout_trial_11
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_ofc_condition_XMREAWDCUE.mat classify_heldout_trial_11
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_striatum_condition_CGWYLACFRU.mat classify_heldout_trial_11
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_striatum_condition_GGOMOTCOIB.mat classify_heldout_trial_11
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_vmpfc_condition_CGWYLACFRU.mat classify_heldout_trial_11
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_vmpfc_condition_BAFRJIOGWD.mat classify_heldout_trial_11
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_rlpfc_condition_QPCOVZBOEM.mat classify_heldout_trial_11
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_rlpfc_condition_HZCSNFKSKO.mat classify_heldout_trial_11
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_bg_condition_JKXIIKNFWA.mat classify_heldout_trial_11
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_bg_condition_FBMJJOHWOJ.mat classify_heldout_trial_11
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_pallidum_condition_JKXIIKNFWA.mat classify_heldout_trial_11
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_pallidum_condition_VHEXKPZOTG.mat classify_heldout_trial_11
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_hippocampus_condition_IBMXXJXMKT.mat classify_heldout_trial_12
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_hippocampus_condition_XGZNUFDUGG.mat classify_heldout_trial_12
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_ofc_condition_IBMXXJXMKT.mat classify_heldout_trial_12
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_ofc_condition_OGKLEFOSKO.mat classify_heldout_trial_12
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_striatum_condition_IBMXXJXMKT.mat classify_heldout_trial_12
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_striatum_condition_NUCNMWSADT.mat classify_heldout_trial_12
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_vmpfc_condition_SKZANMDSVV.mat classify_heldout_trial_12
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_vmpfc_condition_CZMWMYMBAE.mat classify_heldout_trial_12
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_rlpfc_condition_XQPHITPKBT.mat classify_heldout_trial_12
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_rlpfc_condition_EGGAIABXUJ.mat classify_heldout_trial_12
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_bg_condition_QFGJLJBXEH.mat classify_heldout_trial_12
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_bg_condition_SABZUCZRGH.mat classify_heldout_trial_12
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_pallidum_condition_BOLYLLFWAN.mat classify_heldout_trial_12
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_pallidum_condition_GZTSVDBGTV.mat classify_heldout_trial_12
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_hippocampus_condition_RFBTSDJRBJ.mat classify_heldout_trial_13
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_hippocampus_condition_FLLNHAUKDP.mat classify_heldout_trial_13
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_ofc_condition_BHLJIEBPGG.mat classify_heldout_trial_13
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_ofc_condition_CCHSJJFHNH.mat classify_heldout_trial_13
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_striatum_condition_RFBTSDJRBJ.mat classify_heldout_trial_13
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_striatum_condition_QDTGKPRVTZ.mat classify_heldout_trial_13
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_vmpfc_condition_RFBTSDJRBJ.mat classify_heldout_trial_13
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_vmpfc_condition_XBMMDTIJHK.mat classify_heldout_trial_13
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_rlpfc_condition_RFBTSDJRBJ.mat classify_heldout_trial_13
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_rlpfc_condition_QMIZEBYPDA.mat classify_heldout_trial_13
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_bg_condition_KQSHRVCGZR.mat classify_heldout_trial_13
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_bg_condition_SMPIMGUJEP.mat classify_heldout_trial_13
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_pallidum_condition_RFBTSDJRBJ.mat classify_heldout_trial_13
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_pallidum_condition_ILIUSNXSFC.mat classify_heldout_trial_13
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_hippocampus_condition_ZZQFTEPBWV.mat classify_heldout_trial_14
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_hippocampus_condition_CHOMFFLDUN.mat classify_heldout_trial_14
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_ofc_condition_ZZQFTEPBWV.mat classify_heldout_trial_14
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_ofc_condition_NVHUFVDMDU.mat classify_heldout_trial_14
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_striatum_condition_ONGRIVOUEL.mat classify_heldout_trial_14
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_striatum_condition_FUSCMUNOIA.mat classify_heldout_trial_14
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_vmpfc_condition_ONGRIVOUEL.mat classify_heldout_trial_14
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_vmpfc_condition_COVYWADGCV.mat classify_heldout_trial_14
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_rlpfc_condition_WGRBGCYDBP.mat classify_heldout_trial_14
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_rlpfc_condition_HINRITRKYB.mat classify_heldout_trial_14
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_bg_condition_WGRBGCYDBP.mat classify_heldout_trial_14
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_bg_condition_IFFROSBNXB.mat classify_heldout_trial_14
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_pallidum_condition_WGRBGCYDBP.mat classify_heldout_trial_14
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_pallidum_condition_FIDRQYVKMR.mat classify_heldout_trial_14
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_hippocampus_condition_YBLXIJCTJK.mat classify_heldout_trial_15
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_hippocampus_condition_XPIEACNZDG.mat classify_heldout_trial_15
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_ofc_condition_YBLXIJCTJK.mat classify_heldout_trial_15
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_ofc_condition_HXBJHBBSQP.mat classify_heldout_trial_15
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_striatum_condition_UVYSNKPHGD.mat classify_heldout_trial_15
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_striatum_condition_DRCYFIWIDX.mat classify_heldout_trial_15
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_vmpfc_condition_UVYSNKPHGD.mat classify_heldout_trial_15
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_vmpfc_condition_PFWDUOKPJB.mat classify_heldout_trial_15
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_rlpfc_condition_ZZQFTEPBWV.mat classify_heldout_trial_15
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_rlpfc_condition_DMRMFETTAU.mat classify_heldout_trial_15
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_bg_condition_ONGRIVOUEL.mat classify_heldout_trial_15
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_bg_condition_MUEZWSPAFP.mat classify_heldout_trial_15
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_pallidum_condition_UZZSVENUHW.mat classify_heldout_trial_15
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_pallidum_condition_DUHAWQUHRM.mat classify_heldout_trial_15
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_hippocampus_condition_THUZJZNXQX.mat classify_heldout_trial_16
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_hippocampus_condition_ESKIHKAOGR.mat classify_heldout_trial_16
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_ofc_condition_ANWCHKGLOA.mat classify_heldout_trial_16
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_ofc_condition_OPUEVWMSMA.mat classify_heldout_trial_16
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_striatum_condition_ANWCHKGLOA.mat classify_heldout_trial_16
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_striatum_condition_LIQWKGAXQO.mat classify_heldout_trial_16
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_vmpfc_condition_ULWBRUDAWX.mat classify_heldout_trial_16
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_vmpfc_condition_ILDHXZGNHT.mat classify_heldout_trial_16
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_rlpfc_condition_ULWBRUDAWX.mat classify_heldout_trial_16
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_rlpfc_condition_LSNEUWHOPQ.mat classify_heldout_trial_16
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_bg_condition_ULWBRUDAWX.mat classify_heldout_trial_16
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_bg_condition_OBBFICTHKH.mat classify_heldout_trial_16
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_pallidum_condition_AIXAOWATHY.mat classify_heldout_trial_16
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_pallidum_condition_ZITWTZNZFZ.mat classify_heldout_trial_16
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_hippocampus_condition_TYVKCKYPKQ.mat classify_heldout_trial_17
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_hippocampus_condition_LWCBDRGQWQ.mat classify_heldout_trial_17
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_ofc_condition_TYVKCKYPKQ.mat classify_heldout_trial_17
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_ofc_condition_ZSMDJAHTZQ.mat classify_heldout_trial_17
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_striatum_condition_TYVKCKYPKQ.mat classify_heldout_trial_17
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_striatum_condition_WAONXQLNRC.mat classify_heldout_trial_17
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_vmpfc_condition_TYVKCKYPKQ.mat classify_heldout_trial_17
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_vmpfc_condition_UZIOPUJCRJ.mat classify_heldout_trial_17
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_rlpfc_condition_KLXQRUCSYA.mat classify_heldout_trial_17
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_rlpfc_condition_LKPKGEHNUU.mat classify_heldout_trial_17
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_bg_condition_XBTTGATLYH.mat classify_heldout_trial_17
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_bg_condition_GVFLRDAQSE.mat classify_heldout_trial_17
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_pallidum_condition_SSEEAGMFUW.mat classify_heldout_trial_17
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_pallidum_condition_NNAENXTAJG.mat classify_heldout_trial_17
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_hippocampus_condition_DTJYVAPPHH.mat classify_heldout_trial_18
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_hippocampus_condition_XDWXMOAFWJ.mat classify_heldout_trial_18
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_ofc_condition_ZRGZEKCRKX.mat classify_heldout_trial_18
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_ofc_condition_VPLMGAVJRJ.mat classify_heldout_trial_18
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_striatum_condition_ZRGZEKCRKX.mat classify_heldout_trial_18
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_striatum_condition_VSWWKLFQDM.mat classify_heldout_trial_18
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_vmpfc_condition_FSFRDGKWFR.mat classify_heldout_trial_18
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_vmpfc_condition_IFRYJTQKDT.mat classify_heldout_trial_18
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_rlpfc_condition_FSFRDGKWFR.mat classify_heldout_trial_18
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_rlpfc_condition_RJAFMSWNFX.mat classify_heldout_trial_18
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_bg_condition_QAMTDFVUBY.mat classify_heldout_trial_18
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_bg_condition_AOLQXGIXCD.mat classify_heldout_trial_18
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_pallidum_condition_QAMTDFVUBY.mat classify_heldout_trial_18
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_pallidum_condition_FKFLDUPJUI.mat classify_heldout_trial_18
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_hippocampus_condition_LUBGSMICBJ.mat classify_heldout_trial_19
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_hippocampus_condition_ZMALCMXOHM.mat classify_heldout_trial_19
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_ofc_condition_MSGHNNRZNE.mat classify_heldout_trial_19
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_ofc_condition_HBYMXNTGPX.mat classify_heldout_trial_19
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_striatum_condition_MSGHNNRZNE.mat classify_heldout_trial_19
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_striatum_condition_ZMSUKIRNEO.mat classify_heldout_trial_19
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_vmpfc_condition_MSGHNNRZNE.mat classify_heldout_trial_19
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_vmpfc_condition_RMLJJWOYOB.mat classify_heldout_trial_19
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_rlpfc_condition_BJXGPGEKME.mat classify_heldout_trial_19
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_rlpfc_condition_SGWXXDWVGA.mat classify_heldout_trial_19
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_bg_condition_XSLBHVRBBC.mat classify_heldout_trial_19
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_bg_condition_LZCTJCBWPY.mat classify_heldout_trial_19
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_pallidum_condition_BNGQOOQVXF.mat classify_heldout_trial_19
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_pallidum_condition_PEWOAZRCEF.mat classify_heldout_trial_19
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_hippocampus_condition_KQISMCFOKU.mat classify_heldout_trial_20
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_hippocampus_condition_TKIMGCBMBH.mat classify_heldout_trial_20
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_ofc_condition_SHCJEIGUIE.mat classify_heldout_trial_20
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_ofc_condition_ITEPIWUVRU.mat classify_heldout_trial_20
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_striatum_condition_JDAADPFEQL.mat classify_heldout_trial_20
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_striatum_condition_OJUEEXKBMX.mat classify_heldout_trial_20
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_vmpfc_condition_OSIJBKMSGN.mat classify_heldout_trial_20
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_vmpfc_condition_ANVCFTFMVQ.mat classify_heldout_trial_20
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_rlpfc_condition_FOUWXRXSEY.mat classify_heldout_trial_20
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_rlpfc_condition_ZPYUJVSUDM.mat classify_heldout_trial_20
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_bg_condition_FOUWXRXSEY.mat classify_heldout_trial_20
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_bg_condition_AOEWTRIICZ.mat classify_heldout_trial_20
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_train_cvglmnet_pallidum_condition_OBGQFGVQFB.mat classify_heldout_trial_20
rsync -avh --rsh="/usr/local/bin/sshpass -p Mainatati13 ssh -o StrictHostKeyChecking=no -l mtomov13" mtomov13@ncfws13.rc.fas.harvard.edu:/net/rcss11/srv/export/ncf_gershman/share_root/Lab/scripts/matlab/ConLearn/classify_test_cvglmnet_pallidum_condition_VHSBFDMVPC.mat classify_heldout_trial_20




























